

[0;32m### Running tests ### [0m

PYTHONPATH=. py.test tests
============================= test session starts ==============================
platform linux2 -- Python 2.7.6, pytest-2.9.2, py-1.4.31, pluggy-0.3.1
rootdir: /home/ubuntu/workspace, inifile: 
plugins: cov-2.2.1
collected 19 items

tests/test_main.py ....F.........F
tests/test_operations.py ....

=================================== FAILURES ===================================
_______________________ TestCalculator.test_get_history ________________________

self = <tests.test_main.TestCalculator testMethod=test_get_history>

    @freeze_time('2016-05-20T12:00:00Z')
    def test_get_history(self):
        perform_operation(self.calc, 'add', (1, 2))
        perform_operation(self.calc, 'add', (5, 10))
        expected = [
            ('2016-05-20 12:00:00', 'add', (1, 2), 3),
            ('2016-05-20 12:00:00', 'add', (5, 10), 15),
        ]
>       self.assertEqual(get_history(self.calc), expected)
E       AssertionError: Lists differ: [[FakeDatetime(2016, 5, 20, 12... != [('2016-05-20 12:00:00', 'add'...
E       
E       First differing element 0:
E       [FakeDatetime(2016, 5, 20, 12, 0), 'add', (1, 2), <function <lambda> at 0x2b6dfc80c8c0>]
E       ('2016-05-20 12:00:00', 'add', (1, 2), 3)
E       
E       + [('2016-05-20 12:00:00', 'add', (1, 2), 3),
E       +  ('2016-05-20 12:00:00', 'add', (5, 10), 15)]
E       - [[FakeDatetime(2016, 5, 20, 12, 0),
E       -   'add',
E       -   (1, 2),
E       -   <function <lambda> at 0x2b6dfc80c8c0>],
E       -  [FakeDatetime(2016, 5, 20, 12, 0),
E       -   'add',
E       -   (5, 10),
E       -   <function <lambda> at 0x2b6dfc80c8c0>]]

tests/test_main.py:86: AssertionError
______________________ TestCalculator.test_reset_history _______________________

self = <tests.test_main.TestCalculator testMethod=test_reset_history>

    @freeze_time('2016-05-20T12:00:00Z')
    def test_reset_history(self):
        perform_operation(self.calc, 'add', (1, 2))
        perform_operation(self.calc, 'add', (5, 10))
        expected = [
            ('2016-05-20 12:00:00', 'add', (1, 2), 3),
            ('2016-05-20 12:00:00', 'add', (5, 10), 15),
        ]
>       self.assertEqual(get_history(self.calc), expected)
E       AssertionError: Lists differ: [[FakeDatetime(2016, 5, 20, 12... != [('2016-05-20 12:00:00', 'add'...
E       
E       First differing element 0:
E       [FakeDatetime(2016, 5, 20, 12, 0), 'add', (1, 2), <function <lambda> at 0x2b6dfce16aa0>]
E       ('2016-05-20 12:00:00', 'add', (1, 2), 3)
E       
E       + [('2016-05-20 12:00:00', 'add', (1, 2), 3),
E       +  ('2016-05-20 12:00:00', 'add', (5, 10), 15)]
E       - [[FakeDatetime(2016, 5, 20, 12, 0),
E       -   'add',
E       -   (1, 2),
E       -   <function <lambda> at 0x2b6dfce16aa0>],
E       -  [FakeDatetime(2016, 5, 20, 12, 0),
E       -   'add',
E       -   (5, 10),
E       -   <function <lambda> at 0x2b6dfce16aa0>]]

tests/test_main.py:106: AssertionError
===================== 2 failed, 17 passed in 1.22 seconds ======================
